FROM ghcr.io/commaai/openpilot-base:64db514d41eea2ffbed01998708596b7429f1fa5

ENV PYTHONUNBUFFERED=1

ENV OPENPILOT_PATH=/home/batman/openpilot
ENV PYTHONPATH=${OPENPILOT_PATH}:${PYTHONPATH}

RUN mkdir -p ${OPENPILOT_PATH}
WORKDIR ${OPENPILOT_PATH}

COPY . ${OPENPILOT_PATH}/

RUN scons --cache-readonly -j$(nproc)
